title: "Eli Goldberg"
description: "Music Educator & Performer"
baseurl: "Eli-Goldberg-site"
url: "https://photonathan.github.io"
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

author:
  name: "Eli Goldberg"
  email: "MrEliGoldberg@gmail.com"
  avatar: "/assets/images/headshot.jpg"
  bio: "Music Educator | Vocalist | Trombonist"

minimal_mistakes_skin: "default"
paginate: 5

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
