title: "mreligoldberg.com"
email: "MrEliGoldberg@gmail.com"
description: "Eli Goldberg — Music teacher, performer, accompanist, and conductor. Teaching K–12, private lessons, and ensemble direction."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mreligoldberg.com" # the base hostname & protocol for your site, e.g. https://example.com
show_posts: false
# Placeholders for Open Graph
og_image: "/assets/img/og-placeholder.jpg"
favicon: "/assets/img/favicon.svg"
permalink: /:title/
